trigger:
- main

pool:
  name: INFRASYSTEM_POOL

variables: 
   
  - name: resourceGroupName
    value: RG-SYSTEME-FRACE-001-TEST
  
  - name: location
    value: francecentral
  
  - name: virtualNetworkName
    value: VNET-SYSTEME-FRACE-001

  - name: functionAppName
    value: funcswapnsgtrafficxyz
  
  - name: azureResourceManagerConnection
    value: 'IRP INFRAS SYSTEM SP'

steps:

- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/funcapp'
    includeRootFolder: false
    archiveType: zip
    archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
    replaceExistingArchive: true
- task: AzureFunctionApp@2
  displayName: Deploy Azure function Code
  inputs:
    connectedServiceNameARM: $(azureResourceManagerConnection)
    appType: 'functionApp'
    appName: '$(functionAppName)'
    package: '$(Build.ArtifactStagingDirectory)/**/*.zip'
    deploymentMethod: 'auto'

