trigger:
- main

pool:
  vmImage: ubuntu-latest

variables: 
   
  - name: resourceGroupName
    value: RG-CLD-QUA-FRACE-001
  
  - name: location
    value: francecentral
  
  - name: virtualNetworkName
    value: VNET-SYSTEME-FRACE-001

  - name: functionAppName
    value: funcctnvbquafrace001
  
  - name: azureResourceManagerConnection
    value: 'IRP INFRAS SYSTEM SP'

steps:
- task: AzurePowerShell@5
  displayName: Deploy Resource Group
  inputs:
    azureSubscription: $(azureResourceManagerConnection)
    ScriptType: 'FilePath'
    ScriptPath: '$(System.DefaultWorkingDirectory)/scripts/resourceGroup.ps1'
    ScriptArguments: '-resourceGroupName "$(resourceGroupName)" -resourceGroupLocation "$(location)" '
    azurePowerShellVersion: 'LatestVersion' 

- task: AzurePowerShell@5
  displayName: Deploy Virtual network
  inputs:
    azureSubscription: $(azureResourceManagerConnection)
    ScriptType: 'FilePath'
    ScriptPath: '$(System.DefaultWorkingDirectory)/scripts/virtualNetwork.ps1'
    ScriptArguments: '-resourceGroupName "RG-SYSTEME-FRACE-001" -resourceGroupLocation "$(location)" -virtualNetworkName "$(virtualNetworkName)" -environment "sandbox" '
    azurePowerShellVersion: 'LatestVersion'

- task: AzurePowerShell@5
  displayName: Deploy Azure Function App
  inputs:
    azureSubscription: $(azureResourceManagerConnection)
    ScriptType: 'FilePath'
    ScriptPath: '$(System.DefaultWorkingDirectory)/scripts/functionapp.ps1'
    azurePowerShellVersion: 'LatestVersion'


- task: AzurePowerShell@5
  displayName: Deploy Virtual Network Peering
  enabled : false
  inputs:
    azureSubscription: $(azureResourceManagerConnection)
    ScriptType: 'FilePath'
    ScriptPath: '$(System.DefaultWorkingDirectory)/scripts/virtualNetworkPeering.ps1'
    azurePowerShellVersion: 'LatestVersion'




