trigger:
- main

pool:
  vmImage: ubuntu-latest

variables: 
   
  - name: resourceGroupName
    value: RG-CLD-QUA-FRACE-001
  
  - name: location
    value: francecentral
  
  - name: virtualNetworkName
    value: VNET-SYSTEME-FRACE-001

  - name: functionAppName
    value: funcctnvbquafrace001
  
  - name: azureResourceManagerConnection
    value: 'IRP INFRAS SYSTEM SP'

steps:
- task: AzurePowerShell@5
  displayName: Deploy Resource Group
  inputs:
    azureSubscription: $(azureResourceManagerConnection)
    ScriptType: 'FilePath'
    ScriptPath: '$(System.DefaultWorkingDirectory)/scripts/resourceGroup.ps1'
    ScriptArguments: '-resourceGroupName "$(resourceGroupName)" -resourceGroupLocation "$(location)" '
    azurePowerShellVersion: 'LatestVersion' 
- task: AzurePowerShell@5
  displayName: Deploy Virtual network
  inputs:
    azureSubscription: $(azureResourceManagerConnection)
    ScriptType: 'FilePath'
    ScriptPath: '$(System.DefaultWorkingDirectory)/scripts/virtualNetwork.ps1'
    ScriptArguments: '-resourceGroupName "RG-SYSTEME-FRACE-001" -resourceGroupLocation "$(location)" -virtualNetworkName "$(virtualNetworkName)" -environment "sandbox" '
    azurePowerShellVersion: 'LatestVersion'

- task: AzurePowerShell@5
  displayName: Deploy Storage account Network Security Group 
  inputs:
    azureSubscription: $(azureResourceManagerConnection)
    ScriptType: 'FilePath'
    ScriptPath: '$(System.DefaultWorkingDirectory)/scripts/addNetworkSecurityRules.ps1'
    ScriptArguments: '-resourceGroupName "RG-SYSTEME-FRACE-001" -nsgName "nsg-stcld002-qua-001" -ruleName "DenyAnyCustomAnyInbound" -priority "100" -sourceIP "*" -destinationIP "10.20.32.4" -access "Deny"  '
    azurePowerShellVersion: 'LatestVersion'

- task: AzurePowerShell@5
  displayName: Deploy AllowVeeamVmToFunctionApp Network Security Group 
  inputs:
    azureSubscription: $(azureResourceManagerConnection)
    ScriptType: 'FilePath'
    ScriptPath: '$(System.DefaultWorkingDirectory)/scripts/addNetworkSecurityRules.ps1'
    ScriptArguments: '-resourceGroupName "RG-SYSTEME-FRACE-001" -nsgName "nsg-stcld002-qua-001" -ruleName "AllowVeeamVmToFunctionApp" -priority "110" -sourceIP "10.20.0.4" -destinationIP "10.20.1.4" -access "Allow" '
    azurePowerShellVersion: 'LatestVersion'

- task: AzurePowerShell@5
  displayName: Deploy DenyAnyFunctionAppCall Network Security Group 
  inputs:
    azureSubscription: $(azureResourceManagerConnection)
    ScriptType: 'FilePath'
    ScriptPath: '$(System.DefaultWorkingDirectory)/scripts/addNetworkSecurityRules.ps1'
    ScriptArguments: '-resourceGroupName "RG-SYSTEME-FRACE-001" -nsgName "nsg-stcld002-qua-001" -ruleName "DenyAnyFunctionAppCall" -priority "120" -sourceIP "*" -destinationIP "*" -access "Deny" '
    azurePowerShellVersion: 'LatestVersion'

- task: AzurePowerShell@5
  displayName: Deploy Azure Function App
  inputs:
    azureSubscription: $(azureResourceManagerConnection)
    ScriptType: 'FilePath'
    ScriptPath: '$(System.DefaultWorkingDirectory)/scripts/test.ps1'
    azurePowerShellVersion: 'LatestVersion'

# - task: AzurePowerShell@5
#   displayName: Deploy Azure Function App
#   inputs:
#     azureSubscription: $(azureResourceManagerConnection)
#     ScriptType: 'FilePath'
#     ScriptPath: '$(System.DefaultWorkingDirectory)/scripts/functionapp.ps1'
#     ScriptArguments: '-resourceGroupName "$(resourceGroupName)" -resourceGroupLocation "$(location)" -functionAppName "$(functionAppName)" '
#     azurePowerShellVersion: 'LatestVersion'

- task: AzurePowerShell@5
  displayName: Deploy Virtual Network Peering
  enabled : false
  inputs:
    azureSubscription: $(azureResourceManagerConnection)
    ScriptType: 'FilePath'
    ScriptPath: '$(System.DefaultWorkingDirectory)/scripts/virtualNetworkPeering.ps1'
    azurePowerShellVersion: 'LatestVersion'




